# Generated by Django 4.2.5 on 2023-09-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='file',
        ),
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
