# Generated by Django 4.2.4 on 2023-09-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_user'),
        ('companies', '0004_remove_review_file_alter_review_publish_date'),
    ]

    operations = [
    ]
