# Generated by Django 4.2.5 on 2023-09-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_merge_20230910_1445'),
        ('companies', '0005_merge_20230910_1501'),
    ]

    operations = [
    ]
