# Generated by Django 4.2.4 on 2023-09-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_merge_20230910_1430'),
        ('companies', '0006_merge_20230911_0327'),
    ]

    operations = [
    ]
