# Generated by Django 4.2.4 on 2023-09-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='company',
        ),
        migrations.AddField(
            model_name='favorite',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.review'),
            preserve_default=False,
        ),
    ]
